version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # Desabilitar o aviso "mbind: Operation not permitted"
  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8087:8080
